import type { ContentCategory } from "./content";

/**
 * HSK system the Reading Path is anchored to.
 *
 * - "newest-1..6": HSK 3.0 (the 2021 nine-level standard). Only levels 1-6 are
 *   exposed in the UI today; the data model and coverage logic already accept
 *   7-9 so they can be turned on later without a rewrite.
 */
export const HSK_SYSTEM = "newest-1..6" as const;
export type HskSystem = typeof HSK_SYSTEM;

/** HSK levels exposed in the Reading Path UI today. */
export type HskUiLevel = 1 | 2 | 3 | 4 | 5 | 6;
export const HSK_UI_LEVELS: HskUiLevel[] = [1, 2, 3, 4, 5, 6];

/** Full HSK 3.0 level range, including the not-yet-exposed advanced band. */
export type HskAllLevel = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
export const HSK_ALL_LEVELS: HskAllLevel[] = [1, 2, 3, 4, 5, 6, 7, 8, 9];

export type LibrarySourceType =
  | "original"
  | "news_explainer"
  | "adapted_public_domain"
  | "cultural_explainer";

export type LibraryDifficulty = "easy" | "standard" | "challenge";

export interface ParagraphTranslation {
  zh: string;
  en: string;
  /** Optional references to sentenceExplanations ids in expanded library data. */
  sentenceIds?: string[];
}

export interface ComprehensionQuestion {
  id?: string;
  type?: string;
  questionZh: string;
  questionEn?: string;
  /** Some library exports provide the Chinese/source answer separately. */
  answer?: string;
  /** Preferred English answer for the reader. */
  answerEn?: string;
  choices?: string[];
  explanationEn?: string;
}

export interface SentenceExplanationGrammar {
  pattern: string;
  label?: string;
  explanationEn?: string;
  /** Compatibility with hand-authored data that uses `explanation`. */
  explanation?: string;
  hskLevel?: number;
  exampleZh?: string;
  exampleEn?: string;
}

export interface SentenceExplanationPhrase {
  zh: string;
  en: string;
  /** Tone-marked pinyin for the Chinese phrase. */
  pinyin: string;
  note?: string;
  hskLevel?: number;
}

/**
 * Authored, per-sentence reader support stored in the static library JSON.
 * It deliberately keeps the JSON's zh/en naming; the reader converts it to
 * its UI shape at the boundary rather than making authors write UI-specific
 * field names.
 */
export interface SentenceExplanationStatic {
  id?: string;
  zh: string;
  en: string;
  grammar?: SentenceExplanationGrammar[];
  phrases?: SentenceExplanationPhrase[];
  notes?: string[];
  casualNotes?: string[];
  naturalMeaning?: string;
}

export interface LibrarySourceRef {
  label: string;
  url?: string;
}

/**
 * The canonical shape for a library passage. Static — every field is
 * authored ahead of time so no AI call is needed at runtime.
 *
 * Coverage fields (coveredHskWords / newHskWords / aboveLevelWords) are
 * generated by `npm run hsk:coverage` and may be empty / stale until that
 * script has been run.
 */
export interface LibraryItem {
  id: string;
  slug: string;
  titleZh: string;
  titleEn: string;
  hskLevel: HskUiLevel;
  category: ContentCategory;
  subcategory?: string;
  sourceType: LibrarySourceType;
  difficulty: LibraryDifficulty;
  difficultyLabel?: string;
  estimatedChars?: number;
  estimatedWords?: number;
  estimatedMinutes?: number;
  /** Words this passage is meant to teach / surface. */
  targetWords?: string[];
  /** Filled by the coverage script: words from the level set that appear in textZh. */
  coveredHskWords?: string[];
  /** Filled by the coverage script: words newly introduced at this level. */
  newHskWords?: string[];
  /** Words above the passage's HSK level — kept low at HSK 1-3, allowed at 4-6. */
  aboveLevelWords?: string[];
  grammarFocus?: string[];
  tags?: string[];
  summaryEn: string;
  textZh: string;
  /** Older library exports use `translation`; expanded exports include both. */
  translation?: string;
  translationEn?: string;
  /**
   * Paragraph-aligned bilingual pairs. When present every `zh` should
   * concatenate (joined by paragraph breaks) back to `textZh`.
   */
  paragraphTranslations?: ParagraphTranslation[];
  sentenceExplanations?: SentenceExplanationStatic[];
  comprehensionQuestions?: ComprehensionQuestion[];
  /** Required when sourceType === "news_explainer". */
  factCheckNotes?: string;
  sources?: LibrarySourceRef[];
  dateAdded?: string;
  allowedExceptions?: string[];
}

/** Small, serializable subset sent to the client-side Library browser. */
export type LibraryListItem = Pick<
  LibraryItem,
  | "id"
  | "slug"
  | "titleZh"
  | "titleEn"
  | "hskLevel"
  | "category"
  | "difficulty"
  | "summaryEn"
  | "targetWords"
> & {
  characterCount: number;
  textPreview: string;
};

/**
 * Required fields for every library item. The validation script and the
 * content-authoring guide both reference this list — keep it in sync.
 */
export const LIBRARY_REQUIRED_FIELDS: readonly (keyof LibraryItem)[] = [
  "id",
  "slug",
  "titleZh",
  "titleEn",
  "hskLevel",
  "category",
  "sourceType",
  "difficulty",
  "summaryEn",
  "textZh",
] as const;
